### PR TITLE
Wrap unsafe functions to catch errors in debug

### LINKED ISSUE #16: replace unsafe hint function calls with panic-in-debug versions
[`std::slice::get_unchecked`](https://doc.rust-lang.org/std/primitive.slice.html#method.get_unchecked) is _always_ unchecked, but its use in `yaxpeax-x86` is as an optimization, not for load-bearing correctness. it would be helpful to panic if the expectation is violated in debug builds, instead of veering off into unknown states. the same applies for uses of `unreachable_unchecked()` in `yaxpeax-x86`.

for both hints, it would be good to have a wrapper that panics in debug builds, but is _just_ the hint for release builds. maybe a `debug_assert`, maybe an `cfg_if` between two impls, either should be fine. but `yaxpeax-x86` is well at the point that these unsafe hints should be designed to be caught by tests or fuzzing if they become erroneous.

### PR DESCRIPTION
**Pull request by ghost**
The use of `get_kinda_unchecked` as a name is needed for the slice indexing, since inherent impls seem to shadow trait impls. Which is fine.

For the unreachable_unchecked, I just import the safer variant on top of it, which keeps the diff size down.

Closes https://github.com/iximeow/yaxpeax-x86/issues/16 (?)

### CODE REVIEW

**Comment by iximeow** [comment]
fantastic, thank you for the contribution! sorry for the delay, i wanted to make sure i had time to double-check if there would be performance impact (as unexpected as it would be).

it turns out that there was some; the in-tree benchmark was around 3.5% slower after applying `dba409c`. `objdump` and `diff` got me to what i think was the root of it pretty quickly, and adding `#[inline(always)]` on both helpers makes benchmarks build with identical code with or without these changes. i wrote up what i noticed and why i think this makes sense in the commit i added here, [`e22d87c`](https://github.com/iximeow/yaxpeax-x86/pull/17/commits/e22d87cf48475d757c81c3bec8ea40685ef92fc5).

**Comment by ghost** [comment]
sweet, thanks!

Interesting, so the codegen was changed despite the functions seemingly being inlined *anyways*?

**Comment by iximeow** [comment]
yeah, i'm not super familiar with how rustc would compile this but i think with the inline annotation, inlining happens earlier in the process (in MIR?). if it's left to inline later, the call might keep some value alive longer than necessary - maybe related having to pass the index as a distinct argument? so that seems to have left a value alive longer than necessary _after_ inlining, then `rdi` remains "used" where it was free before, and llvm is forced to pick `rbp` with the slightly larger instructions to encode its use.

i ran into a bunch of this for the [`AnnotatingDecoder`](https://github.com/iximeow/yaxpeax-x86/blob/no-gods-no-/src/long_mode/mod.rs#L4174-L4195) stuff too, but worse. for perf-sensitive users there's a no-op `DescriptionSink` so all those calls _should_ be free,  but just having calls present - even though they're removed later - tripped up some inlining thresholds and significantly degraded throughput. i suspect yaxpeax-x86 is quite far off from the shape of code llvm's heuristics anticipate so this kinda just.. happens. but i don't have it in me to ... yak... shave that far down :)

**Comment by iximeow** [comment]
.. actually, this is really strong evidence that i should spend more time thinking about how to conserve code size, if an extra 32 bytes of code was so impactful. neat!

**Pull request merged**
